---------------------------Employee Vaccination Drive---------------------------

Task 1: Read Employee data in sampleEmployee dataframe from here https://www.briandunning.com/sample-data/us-500.zip

In [182]:
import zipfile
from urllib.request import urlopen
import shutil
import os
import pandas as pd

In [183]:
url = 'https://www.briandunning.com/sample-data/us-500.zip'
file_name = 'us-500.zip'
with urlopen(url) as response, open(file_name, 'wb') as out_file:
    shutil.copyfileobj(response, out_file)
    with zipfile.ZipFile(file_name) as zf:
        zf.extract('us-500.csv')
os.remove('us-500.zip')
sampleEmployee = pd.read_csv('us-500.csv')

In [184]:
sampleEmployee.head(10)

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com
5,Simona,Morasca,"Chapman, Ross E Esq",3 Mcauley Dr,Ashland,Ashland,OH,44805,419-503-2484,419-800-6759,simona@morasca.com,http://www.chapmanrosseesq.com
6,Mitsue,Tollner,Morlong Associates,7 Eads St,Chicago,Cook,IL,60632,773-573-6914,773-924-8565,mitsue_tollner@yahoo.com,http://www.morlongassociates.com
7,Leota,Dilliard,Commercial Press,7 W Jackson Blvd,San Jose,Santa Clara,CA,95111,408-752-3500,408-813-1105,leota@hotmail.com,http://www.commercialpress.com
8,Sage,Wieser,Truhlar And Truhlar Attys,5 Boston Ave #88,Sioux Falls,Minnehaha,SD,57105,605-414-2147,605-794-4895,sage_wieser@cox.net,http://www.truhlarandtruhlarattys.com
9,Kris,Marrier,"King, Christopher A Esq",228 Runamuck Pl #2808,Baltimore,Baltimore City,MD,21224,410-655-8723,410-804-4694,kris@gmail.com,http://www.kingchristopheraesq.com

Task 2: Using this sampleEmployee dataframe create 100X more data points and store it into employeeDF ( this will have 50,000 rows )

In [185]:
temp1=sampleEmployee[['first_name', 'last_name']]

In [186]:
temp2=sampleEmployee[[ 'company_name', 'address', 'city', 'county',
       'state', 'zip', 'web']]

In [187]:
df=temp1.merge(temp2, how='cross')

In [188]:
df

,first_name,last_name,company_name,address,city,county,state,zip,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,http://www.bentonjohnbjr.com
1,James,Butt,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,http://www.chanayjeffreyaesq.com
2,James,Butt,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,http://www.chemeljameslcpa.com
3,James,Butt,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,http://www.feltzprintingservice.com
4,James,Butt,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,http://www.printingdimensions.com
...,...,...,...,...,...,...,...,...,...
249995,Chauncey,Motley,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com
249996,Chauncey,Motley,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com
249997,Chauncey,Motley,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com
249998,Chauncey,Motley,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com
249999,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com

In [189]:
dfmerge = df.merge(sampleEmployee, how='left',indicator=True)

In [190]:
dfmerge

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email,_merge
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,http://www.bentonjohnbjr.com,504-621-8927,504-845-1427,jbutt@gmail.com,both
1,James,Butt,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,http://www.chanayjeffreyaesq.com,NaN,NaN,NaN,left_only
2,James,Butt,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,http://www.chemeljameslcpa.com,NaN,NaN,NaN,left_only
3,James,Butt,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,http://www.feltzprintingservice.com,NaN,NaN,NaN,left_only
4,James,Butt,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,http://www.printingdimensions.com,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Chauncey,Motley,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com,NaN,NaN,NaN,left_only
249996,Chauncey,Motley,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com,NaN,NaN,NaN,left_only
249997,Chauncey,Motley,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com,NaN,NaN,NaN,left_only
249998,Chauncey,Motley,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com,NaN,NaN,NaN,left_only
249999,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com,407-413-4842,407-557-8857,chauncey_motley@aol.com,both

In [191]:
import numpy as np

In [192]:
from pandas.core.internals import concat
for i in range(len(dfmerge)):
  tmp=str(dfmerge.email.iloc[i])
  if tmp=='nan':
    dfmerge.email.iloc[i]= str(dfmerge.first_name.iloc[i])+'.'+str(dfmerge.last_name.iloc[i])+'.'+str(dfmerge.company_name.iloc[i][0:5])+'@gmail.com'

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [193]:
dfmerge

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email,_merge
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,http://www.bentonjohnbjr.com,504-621-8927,504-845-1427,jbutt@gmail.com,both
1,James,Butt,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,http://www.chanayjeffreyaesq.com,NaN,NaN,James.Butt.Chana@gmail.com,left_only
2,James,Butt,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,http://www.chemeljameslcpa.com,NaN,NaN,James.Butt.Cheme@gmail.com,left_only
3,James,Butt,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,http://www.feltzprintingservice.com,NaN,NaN,James.Butt.Feltz@gmail.com,left_only
4,James,Butt,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,http://www.printingdimensions.com,NaN,NaN,James.Butt.Print@gmail.com,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Chauncey,Motley,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com,NaN,NaN,Chauncey.Motley.Inner@gmail.com,left_only
249996,Chauncey,Motley,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com,NaN,NaN,Chauncey.Motley.Herma@gmail.com,left_only
249997,Chauncey,Motley,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com,NaN,NaN,Chauncey.Motley.Simon@gmail.com,left_only
249998,Chauncey,Motley,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com,NaN,NaN,Chauncey.Motley.Wareh@gmail.com,left_only
249999,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com,407-413-4842,407-557-8857,chauncey_motley@aol.com,both

In [196]:
import random
def makeFirst():
    first_digit = random.randint(1,9)
    remaining = random.randint(0,99)
    return first_digit*100 + remaining
def makeSecond():
    middle = 0
    while middle == 0:
        middle1 = random.randint(0,8)
        middle2 = random.randint(0,8)
        middle3 = random.randint(0,8)

        middle = 100*middle1 + 10*middle2 + middle3
    return middle
def makeLast():
    return ''.join(map(str, random.sample(range(10),4)))
def makePhone():
    first = makeFirst()
    second = makeSecond()
    last = makeLast()
    return '{}-{}-{}'.format(first,second,last)
for i in range(len(dfmerge)):
  tmp1=str(dfmerge.phone1.iloc[i])
  tmp2=str(dfmerge.phone2.iloc[i])
  if tmp1=='nan' and tmp2=='nan':
    dfmerge.phone1.iloc[i]= makePhone()
    dfmerge.phone2.iloc[i]= makePhone()

In [197]:

  dfmerge

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email,_merge
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,http://www.bentonjohnbjr.com,504-621-8927,504-845-1427,jbutt@gmail.com,both
1,James,Butt,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,http://www.chanayjeffreyaesq.com,912-787-8760,898-275-3925,James.Butt.Chana@gmail.com,left_only
2,James,Butt,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,http://www.chemeljameslcpa.com,974-414-5864,943-231-1934,James.Butt.Cheme@gmail.com,left_only
3,James,Butt,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,http://www.feltzprintingservice.com,654-833-8564,178-115-1429,James.Butt.Feltz@gmail.com,left_only
4,James,Butt,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,http://www.printingdimensions.com,504-252-4590,284-775-1652,James.Butt.Print@gmail.com,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,Chauncey,Motley,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com,339-446-8607,981-67-5721,Chauncey.Motley.Inner@gmail.com,left_only
249996,Chauncey,Motley,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com,256-38-2314,609-85-6193,Chauncey.Motley.Herma@gmail.com,left_only
249997,Chauncey,Motley,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com,652-550-8671,787-788-6791,Chauncey.Motley.Simon@gmail.com,left_only
249998,Chauncey,Motley,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com,344-557-0216,909-832-8695,Chauncey.Motley.Wareh@gmail.com,left_only
249999,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com,407-413-4842,407-557-8857,chauncey_motley@aol.com,both

In [198]:
df1_only = dfmerge[dfmerge['_merge'] == 'left_only']

In [199]:
df1=df1_only.sample(n = 49500)

In [200]:
df2= df1.drop('_merge', axis=1)

In [201]:
df2

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email
243601,Gail,Similton,Pacific Grove Museum Ntrl Hist,524 Louisiana Ave Nw,San Leandro,Alameda,CA,94577,http://www.pacificgrovemuseumntrlhist.com,843-810-3476,470-288-6391,Gail.Similton.Pacif@gmail.com
196873,Laurel,Pagliuca,"Solove, Robert A Esq",49440 Dearborn St,Norwalk,Fairfield,CT,6854,http://www.soloverobertaesq.com,354-828-0473,968-775-3604,Laurel.Pagliuca.Solov@gmail.com
161,James,Butt,Cummins Southern Plains Inc,63381 Jenks Ave,Philadelphia,Philadelphia,PA,19134,http://www.cumminssouthernplainsinc.com,324-315-0869,292-620-5498,James.Butt.Cummi@gmail.com
106463,Beckie,Silvestrini,Ceramic Tile Sales Inc,62260 Park Stre,Monroe Township,Middlesex,NJ,8831,http://www.ceramictilesalesinc.com,887-508-0216,403-482-2583,Beckie.Silvestrini.Ceram@gmail.com
85537,Irma,Wolfgramm,Parkway Company,17 Morena Blvd,Camarillo,Ventura,CA,93012,http://www.parkwaycompany.com,338-663-7024,981-843-9532,Irma.Wolfgramm.Parkw@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
80620,Dierdre,Yum,Bresler Eitel Framg Gllry Ltd,4646 Kaahumanu St,Hackensack,Bergen,NJ,7601,http://www.breslereitelframggllryltd.com,851-722-4192,441-167-2803,Dierdre.Yum.Bresl@gmail.com
9275,Yuki,Whobrey,Development Authority,78112 Morris Ave,North Haven,New Haven,CT,6473,http://www.developmentauthority.com,912-685-3874,693-762-3214,Yuki.Whobrey.Devel@gmail.com
230916,Nan,Koppinger,Harris Corporation,4 Iwaena St,Baltimore,Baltimore City,MD,21202,http://www.harriscorporation.com,430-550-9637,343-436-4370,Nan.Koppinger.Harri@gmail.com
186923,Zona,Colla,Centerline Engineering,86350 Roszel Rd,Phoenix,Maricopa,AZ,85012,http://www.centerlineengineering.com,350-316-2308,710-133-0543,Zona.Colla.Cente@gmail.com
245688,Thaddeus,Ankeny,"Nischwitz, Jeffrey L Esq",4671 Alemany Blvd,Jersey City,Hudson,NJ,7304,http://www.nischwitzjeffreylesq.com,422-166-7529,678-433-6507,Thaddeus.Ankeny.Nisch@gmail.com

In [202]:
employeeDF=pd.concat([df2, sampleEmployee])

In [203]:
employeeDF

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email
243601,Gail,Similton,Pacific Grove Museum Ntrl Hist,524 Louisiana Ave Nw,San Leandro,Alameda,CA,94577,http://www.pacificgrovemuseumntrlhist.com,843-810-3476,470-288-6391,Gail.Similton.Pacif@gmail.com
196873,Laurel,Pagliuca,"Solove, Robert A Esq",49440 Dearborn St,Norwalk,Fairfield,CT,6854,http://www.soloverobertaesq.com,354-828-0473,968-775-3604,Laurel.Pagliuca.Solov@gmail.com
161,James,Butt,Cummins Southern Plains Inc,63381 Jenks Ave,Philadelphia,Philadelphia,PA,19134,http://www.cumminssouthernplainsinc.com,324-315-0869,292-620-5498,James.Butt.Cummi@gmail.com
106463,Beckie,Silvestrini,Ceramic Tile Sales Inc,62260 Park Stre,Monroe Township,Middlesex,NJ,8831,http://www.ceramictilesalesinc.com,887-508-0216,403-482-2583,Beckie.Silvestrini.Ceram@gmail.com
85537,Irma,Wolfgramm,Parkway Company,17 Morena Blvd,Camarillo,Ventura,CA,93012,http://www.parkwaycompany.com,338-663-7024,981-843-9532,Irma.Wolfgramm.Parkw@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com,208-709-1235,208-206-9848,bgillaspie@gillaspie.com
496,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com,574-499-1454,574-330-1884,rkampa@kampa.org
497,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com,308-726-2182,308-250-6987,flo.bookamer@cox.net
498,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com,206-711-6498,206-395-6284,jbiddy@yahoo.com
499,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com,407-413-4842,407-557-8857,chauncey_motley@aol.com

Task 3- The company has to plan a vaccination drive and the priority will be based on employee population in a particular city. Create a dataframe of CityEmployeeDensity, the 1st city will be the one with maxium number of employees

In [210]:
CityEmployeeDensity=employeeDF.groupby(['city'])['city'].count().reset_index(name="count").sort_values(by=['count'], ascending=False)

In [211]:
CityEmployeeDensity

              city  count
200       New York   1360
235   Philadelphia    772
62         Chicago    668
184          Miami    571
277  San Francisco    553
..             ...    ...
111     Fort Worth     83
228        Passaic     82
165    Little Rock     82
31     Bloomington     81
238     Plainfield     80

[342 rows x 2 columns]

In [212]:
CityEmployeeDensity = CityEmployeeDensity.assign(Sequence=range(1,len(CityEmployeeDensity)+1))

In [213]:
CityEmployeeDensity

              city  count  Sequence
200       New York   1360         1
235   Philadelphia    772         2
62         Chicago    668         3
184          Miami    571         4
277  San Francisco    553         5
..             ...    ...       ...
111     Fort Worth     83       338
228        Passaic     82       339
165    Little Rock     82       340
31     Bloomington     81       341
238     Plainfield     80       342

[342 rows x 3 columns]

Task 4:  Please create new dataframe by name "VaccinationDrivePlan" with all columns from employeeDF and additional column "Sequence". In Sequence Column populate the value from the CityEmployeeDensity Dataframe. Print this dataframe

In [216]:
VaccinationDrivePlan =  pd.merge(employeeDF, CityEmployeeDensity, how='left', on = 'city').drop(columns = ['count'])

In [217]:
display(VaccinationDrivePlan)

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email,Sequence
0,Gail,Similton,Pacific Grove Museum Ntrl Hist,524 Louisiana Ave Nw,San Leandro,Alameda,CA,94577,http://www.pacificgrovemuseumntrlhist.com,843-810-3476,470-288-6391,Gail.Similton.Pacif@gmail.com,57
1,Laurel,Pagliuca,"Solove, Robert A Esq",49440 Dearborn St,Norwalk,Fairfield,CT,6854,http://www.soloverobertaesq.com,354-828-0473,968-775-3604,Laurel.Pagliuca.Solov@gmail.com,230
2,James,Butt,Cummins Southern Plains Inc,63381 Jenks Ave,Philadelphia,Philadelphia,PA,19134,http://www.cumminssouthernplainsinc.com,324-315-0869,292-620-5498,James.Butt.Cummi@gmail.com,2
3,Beckie,Silvestrini,Ceramic Tile Sales Inc,62260 Park Stre,Monroe Township,Middlesex,NJ,8831,http://www.ceramictilesalesinc.com,887-508-0216,403-482-2583,Beckie.Silvestrini.Ceram@gmail.com,50
4,Irma,Wolfgramm,Parkway Company,17 Morena Blvd,Camarillo,Ventura,CA,93012,http://www.parkwaycompany.com,338-663-7024,981-843-9532,Irma.Wolfgramm.Parkw@gmail.com,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,32
49996,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com,574-499-1454,574-330-1884,rkampa@kampa.org,234
49997,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com,308-726-2182,308-250-6987,flo.bookamer@cox.net,83
49998,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com,206-711-6498,206-395-6284,jbiddy@yahoo.com,72
49999,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com,407-413-4842,407-557-8857,chauncey_motley@aol.com,9

Task 5: Create a Final Vaccination Schedule with a plan to vaccinate 100 employees in a day Across Cities in Parallel AND Sequential

In [218]:
VaccinationDrivePlan['schedule'] = VaccinationDrivePlan.groupby(['city']).cumcount()

In [220]:
def DaySchedule(schedule):
  return int(schedule/100)+1

In [221]:
VaccinationDrivePlan['Day']= VaccinationDrivePlan['schedule'].map(DaySchedule)

In [222]:
VaccinationDrivePlan

,first_name,last_name,company_name,address,city,county,state,zip,web,phone1,phone2,email,Sequence,schedule,Day
0,Gail,Similton,Pacific Grove Museum Ntrl Hist,524 Louisiana Ave Nw,San Leandro,Alameda,CA,94577,http://www.pacificgrovemuseumntrlhist.com,843-810-3476,470-288-6391,Gail.Similton.Pacif@gmail.com,57,0,1
1,Laurel,Pagliuca,"Solove, Robert A Esq",49440 Dearborn St,Norwalk,Fairfield,CT,6854,http://www.soloverobertaesq.com,354-828-0473,968-775-3604,Laurel.Pagliuca.Solov@gmail.com,230,0,1
2,James,Butt,Cummins Southern Plains Inc,63381 Jenks Ave,Philadelphia,Philadelphia,PA,19134,http://www.cumminssouthernplainsinc.com,324-315-0869,292-620-5498,James.Butt.Cummi@gmail.com,2,0,1
3,Beckie,Silvestrini,Ceramic Tile Sales Inc,62260 Park Stre,Monroe Township,Middlesex,NJ,8831,http://www.ceramictilesalesinc.com,887-508-0216,403-482-2583,Beckie.Silvestrini.Ceram@gmail.com,50,0,1
4,Irma,Wolfgramm,Parkway Company,17 Morena Blvd,Camarillo,Ventura,CA,93012,http://www.parkwaycompany.com,338-663-7024,981-843-9532,Irma.Wolfgramm.Parkw@gmail.com,177,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,Brittni,Gillaspie,Inner Label,67 Rv Cent,Boise,Ada,ID,83709,http://www.innerlabel.com,208-709-1235,208-206-9848,bgillaspie@gillaspie.com,32,285,3
49996,Raylene,Kampa,Hermar Inc,2 Sw Nyberg Rd,Elkhart,Elkhart,IN,46514,http://www.hermarinc.com,574-499-1454,574-330-1884,rkampa@kampa.org,234,98,1
49997,Flo,Bookamer,Simonton Howe & Schneider Pc,89992 E 15th St,Alliance,Box Butte,NE,69301,http://www.simontonhoweschneiderpc.com,308-726-2182,308-250-6987,flo.bookamer@cox.net,83,120,2
49998,Jani,Biddy,Warehouse Office & Paper Prod,61556 W 20th Ave,Seattle,King,WA,98104,http://www.warehouseofficepaperprod.com,206-711-6498,206-395-6284,jbiddy@yahoo.com,72,188,2
49999,Chauncey,Motley,Affiliated With Travelodge,63 E Aurora Dr,Orlando,Orange,FL,32804,http://www.affiliatedwithtravelodge.com,407-413-4842,407-557-8857,chauncey_motley@aol.com,9,475,5

Task 6: Print the final report showing in how many day the vaccination drive is completed per city

In [223]:
for city, temp in VaccinationDrivePlan.groupby('city'):
  print(city,temp['Day'].max())

Aberdeen 1
Abilene 4
Absecon 2
Akron 1
Albany 3
Alliance 2
Amarillo 2
Anaheim 1
Anchorage 4
Ann Arbor 2
Annandale 1
Arlington 1
Arlington Heights 1
Ashland 2
Aston 1
Astoria 1
Atlanta 4
Atlantic City 2
Austin 4
Baltimore 5
Bangor 2
Barberton 2
Beachwood 1
Beaverton 1
Bellflower 2
Beloit 1
Berkeley 1
Beverly Hills 2
Biloxi 1
Bladensburg 2
Bloomfield 1
Bloomington 1
Bohemia 1
Boise 3
Boston 2
Bothell 2
Boulder 2
Bowling Green 2
Brandon 2
Bridgeport 3
Bridgewater 3
Brighton 2
Bronx 2
Brook Park 2
Brooklyn 4
Broussard 1
Bucyrus 2
Buffalo 2
Burlingame 2
Burlington 2
Burnsville 3
Butte 2
Camarillo 2
Cambridge 2
Canton 1
Carson City 2
Cathedral City 1
Cedar Grove 2
Chagrin Falls 2
Chapel Hill 1
Cherry Hill 3
Cheyenne 1
Chicago 7
Cincinnati 4
Clarks Summit 1
Cleveland 2
Clifton 1
Clinton 2
Clovis 1
Coatesville 1
Cocoa 2
College Station 1
Colorado Springs 2
Columbia 3
Columbus 2
Concord 2
Conroe 3
Coram 1
Costa Mesa 2
Crestview 1
Crystal River 1
Dallas 4
Daytona Beach 2
Dearborn 1
Deer Park 1
Denver 5
Denville 2
Des Moines 2
Douglasville 1
Dunellen 1
East Lansing 1
Easton 2
El Cajon 3
El Monte 1
El Paso 1
Elk Grove Village 1
Elkhart 1
Englewood 3
Erie 4
Escondido 2
Eugene 1
Euless 1
Evanston 1
Fairbanks 3
Fairfax 1
Fairfield 2
Fargo 2
Fayetteville 1
Findlay 2
Flemington 1
Fort Wayne 1
Fort Worth 1
Fortville 1
Freehold 2
Garden City 2
Gardena 6
Glen Burnie 1
Grand Rapids 2
Green Bay 2
Greensboro 3
Hackensack 1
Hamilton 2
Hampstead 1
Hanover 1
Harrisburg 2
Harrison 1
Hatfield 2
Hays 2
Hayward 4
Hazleton 2
Hialeah 1
Hicksville 1
High Point 1
Highland Park 1
Hilo 1
Homestead 1
Homosassa 2
Honolulu 3
Hopkins 2
Houma 2
Huntingdon Valley 1
Huntington Beach 1
Hyattsville 2
Indianapolis 5
Irving 3
Jackson 1
Jacksonville 2
Jenkintown 2
Jersey City 4
Johnston 2
Katonah 2
Kearny 3
Kennedale 2
Kent 2
Kerrville 2
King of Prussia 2
Kulpsville 2
La Mesa 2
Lafayette 3
Lake Worth 2
Lancaster 1
Lansing 2
Laredo 1
Las Cruces 2
Little Falls 1
Little Rock 1
Littleton 2
Livingston 2
London 2
Long Island City 2
Longwood 2
Los Angeles 5
Lynbrook 1
Lyndhurst 2
Madison 3
Margate City 1
Massapequa 1
Mc Lean 2
Mc Minnville 2
Memphis 3
Meridian 1
Mesa 2
Mesquite 3
Metairie 2
Miami 6
Middle Island 1
Middleboro 1
Middlesex 2
Milan 1
Milwaukee 6
Minneapolis 2
Monroe Township 3
Moscow 2
Moss 2
Mount Vernon 2
Muskegon 1
Nashville 4
New Bedford 2
New Haven 2
New Orleans 3
New York 14
Newark 3
Newport News 2
Niles 2
North Attleboro 1
North Haven 1
Northfield 1
Northridge 2
Norwalk 1
Novato 2
Nutley 2
Oak Hill 1
Oakland 1
Oakley 1
Old Forge 1
Omaha 2
Ontario 1
Opa Locka 2
Orange 2
Orlando 5
Oroville 2
Overland Park 2
Owings Mills 1
Pacifica 2
Palatine 1
Paramus 1
Parkville 2
Pasadena 1
Passaic 1
Paterson 2
Pearl 2
Pearl City 2
Pelham 2
Peoria 1
Perrysburg 1
Philadelphia 8
Phoenix 5
Pittstown 1
Plainfield 1
Plaistow 2
Plano 1
Pomona 2
Port Jervis 2
Portland 3
Preston 1
Prineville 1
Providence 4
Raleigh 2
Ramsey 1
Randolph 1
Reno 2
Richboro 2
Richland 2
Richmond 2
Ridgefield Park 2
Riverside 2
Riverton 2
Rochester 1
Rock Springs 2
Rockaway 1
Rockford 2
Rohnert Park 2
Rolling Meadows 1
Ronkonkoma 1
Roseville 2
Round Rock 3
Sacramento 2
Saint Joseph 2
Saint Louis 3
Saint Paul 1
Salem 1
Salisbury 1
Salt Lake City 1
San Antonio 2
San Bernardino 1
San Carlos 1
San Diego 3
San Francisco 6
San Gabriel 2
San Jose 5
San Leandro 2
San Mateo 1
San Ramon 2
Santa Ana 2
Santa Clara 2
Santa Rosa 2
Saratoga 2
Satellite Beach 1
Scottsdale 3
Scranton 1
Seattle 2
Shakopee 1
Shawnee 2
Sioux Falls 1
Smithfield 1
Somerset 2
Somerville 2
South Bend 2
South San Francisco 2
Southampton 1
Southfield 2
Spartanburg 1
Staten Island 1
Sterling Heights 2
Stevens Point 2
Stockton 2
Strongsville 2
Syosset 2
Syracuse 2
Tacoma 1
Tampa 2
Taylor 1
Thousand Oaks 2
Thousand Palms 1
Toledo 2
Toms River 1
Trenton 2
Trion 2
Troy 2
Tullahoma 2
Tulsa 2
Union City 1
Utica 1
Valley Park 1
Van Nuys 2
Vashon 1
Vestal 1
Waco 3
Warren 1
Washington 2
Waterford 2
Wayne 1
Wellsville 1
Westborough 2
Westbury 1
Wheeling 2
Whippany 1
Wichita Falls 2
Wilmington 1
Worcester 4
Yonkers 1
York 1